{{- if .Values.trafficGenerator.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "nginx-chart.fullname" . }}-traffic-generator
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.trafficGenerator.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: traffic-generator
        spec:
          restartPolicy: OnFailure
          containers:
            - name: traffic-generator
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  #!/bin/sh
                  
                  SERVICE="http://{{ include "nginx-chart.fullname" . }}"
                  
                  echo "Starting traffic generation to $SERVICE"
                  
                  # Generate 100 requests with equal distribution across all status codes
                  TOTAL_REQUESTS=100
                  echo "Generating $TOTAL_REQUESTS requests (20 per status code)"
                  
                  for i in $(seq 1 $TOTAL_REQUESTS); do
                    # Cycle through status codes equally (20 of each)
                    STATUS_TYPE=$(($i % 5))
                    
                    case $STATUS_TYPE in
                      0)
                        # 200 OK
                        ENDPOINT="/"
                        echo "Request $i: $SERVICE$ENDPOINT (expecting 200)"
                        ;;
                      1)
                        # 404 Not Found
                        ENDPOINT="/error/notfound-$RANDOM"
                        echo "Request $i: $SERVICE$ENDPOINT (expecting 404)"
                        ;;
                      2)
                        # 500 Internal Server Error
                        ENDPOINT="/api/error-$RANDOM"
                        echo "Request $i: $SERVICE$ENDPOINT (expecting 500)"
                        ;;
                      3)
                        # 502 Bad Gateway
                        ENDPOINT="/api/badgateway-$RANDOM"
                        echo "Request $i: $SERVICE$ENDPOINT (expecting 502)"
                        ;;
                      4)
                        # 503 Service Unavailable
                        ENDPOINT="/api/unavailable-$RANDOM"
                        echo "Request $i: $SERVICE$ENDPOINT (expecting 503)"
                        ;;
                    esac
                    
                    # Make request and capture status code
                    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$SERVICE$ENDPOINT" 2>/dev/null || echo "000")
                    echo "  Status: $HTTP_CODE"
                    
                    # Small delay between requests
                    sleep 0.1
                  done
                  
                  echo "Traffic generation complete"
{{- end }}

