apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-chart.fullname" . }}-httpbin
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "nginx-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
